import { buildPlacePage } from '@/lib/content/builders'
import type { PlaceRecord } from '@/lib/content/builders'
import type { SeoPageContent } from '@/lib/content/page-types'

/** Existing static neighborhood routes — do not generate duplicate [slug] pages. */
export const STATIC_NEIGHBORHOOD_SLUGS = [
  'summerlin-west',
  'the-ridges',
  'red-rock-country-club',
  'the-summit',
  'macdonald-ranch',
  'southern-highlands',
  'skye-canyon',
  'mountains-edge',
  'del-webb-north-ranch',
] as const

const records: PlaceRecord[] = [
  {
    slug: 'summerlin',
    name: 'Summerlin',
    city: 'Las Vegas',
    region: 'west Las Vegas master-planned communities',
    propertyMix: 'single-story ranch homes, two-story production homes, and custom estates',
    commute: 'Most Summerlin streets sit 15–25 minutes from the Strip in light traffic and about 10 minutes from Downtown Summerlin retail.',
    amenities: 'Parks, trail connections, golf courses, and the Downtown Summerlin retail core are the features buyers ask about first.',
    challenge: 'Summerlin has constant new and resale competition, so under-photographed homes look dated next to builder inventory.',
    marketingAngle: 'Lead with village, lot orientation, and outdoor living instead of a generic Las Vegas headline.',
    priceContext: 'Summerlin prices span mid-six figures through multi-million custom homes. Use a current CMA; do not copy a citywide average.',
    related: [
      { href: '/neighborhoods/summerlin-west', anchor: 'Summerlin West luxury homes' },
      { href: '/neighborhoods/the-ridges', anchor: 'The Ridges custom estates' },
      { href: '/neighborhoods/affinity-summerlin', anchor: 'Affinity Summerlin condos' },
      { href: '/summerlin-real-estate-agent', anchor: 'Summerlin real estate agent' },
      { href: '/sell-my-house-fast-summerlin', anchor: 'Sell a house fast in Summerlin' },
    ],
  },
  {
    slug: 'affinity-summerlin',
    name: 'Affinity Summerlin',
    city: 'Las Vegas',
    region: 'Summerlin, west Las Vegas',
    propertyMix: 'mid-rise condominiums and lock-and-leave residences near Downtown Summerlin',
    commute: 'Affinity Summerlin is a short drive to Downtown Summerlin retail and typically 20 minutes from the Strip in light traffic.',
    amenities: 'Pooled amenities, Downtown Summerlin shopping, and west-valley trail connections are the features to photograph first.',
    challenge: 'Condo buyers compare HOA dues, rental rules, and finish level building by building. Vague “luxury Summerlin” copy loses the click.',
    marketingAngle: 'Lead with floor-plan size, HOA documents, and walk time to Downtown Summerlin — not a generic Las Vegas headline.',
    priceContext: 'Affinity values move with floor, view, and renovation. Use same-building comps, not a Summerlin single-family average.',
    related: [
      { href: '/condos/summerlin', anchor: 'Summerlin condos for sale' },
      { href: '/neighborhoods/downtown-summerlin', anchor: 'Downtown Summerlin homes' },
      { href: '/neighborhoods/summerlin', anchor: 'Summerlin homes for sale' },
      { href: '/neighborhoods/queensridge', anchor: 'Queensridge luxury homes' },
    ],
  },
  {
    slug: 'henderson',
    name: 'Henderson',
    city: 'Henderson',
    region: 'southeast of the Las Vegas Strip',
    propertyMix: 'production homes, golf-course lots, and mid-rise condos',
    commute: 'Henderson addresses typically run 20–35 minutes to the Strip and 15–25 minutes to Harry Reid International Airport, depending on the village.',
    amenities: 'Trail systems, recreation centers, and golf courses are physical amenities to document in photos and remarks.',
    challenge: 'Henderson buyers compare Green Valley, Anthem, Inspirada, and Seven Hills side by side, so vague “Henderson home” copy loses the click.',
    marketingAngle: 'Name the village, lot size, and outdoor living, then syndicate to Henderson-specific buyer lists.',
    priceContext: 'Henderson ranges widely by village. Price against the same village’s actives, pendings, and expireds — not the Las Vegas MSA headline.',
    related: [
      { href: '/neighborhoods/green-valley', anchor: 'Green Valley homes in Henderson' },
      { href: '/neighborhoods/anthem', anchor: 'Anthem Henderson real estate' },
      { href: '/condos/henderson', anchor: 'Henderson condos' },
      { href: '/henderson-real-estate-agent', anchor: 'Henderson real estate agent' },
    ],
  },
  {
    slug: 'green-valley',
    name: 'Green Valley',
    city: 'Henderson',
    region: 'central Henderson',
    propertyMix: 'established single-family homes, townhomes, and mid-rise condos',
    commute: 'Green Valley sits roughly 20 minutes from the airport and 25 minutes from the Strip in typical traffic.',
    amenities: 'The District at Green Valley Ranch retail, parks, and nearby golf are the location facts to show in listing media.',
    challenge: 'Older elevations compete with newer Henderson villages, so media must show updates honestly or the first tour ends at the door.',
    marketingAngle: 'Show kitchen, bath, and HVAC age clearly. Hide nothing that a Green Valley buyer will inspect on day one.',
    priceContext: 'Green Valley values vary by renovation level and lot. Expired comps in the same tract matter more than a Henderson average.',
    related: [
      { href: '/neighborhoods/henderson', anchor: 'Henderson homes that did not sell' },
      { href: '/condos/the-district', anchor: 'The District at Green Valley condos' },
      { href: '/condos/altair', anchor: 'Altair at Green Valley condos' },
      { href: '/neighborhoods/green-valley-ranch', anchor: 'Green Valley Ranch homes' },
    ],
  },
  {
    slug: 'green-valley-ranch',
    name: 'Green Valley Ranch',
    city: 'Henderson',
    region: 'Green Valley, Henderson',
    propertyMix: 'single-family homes near the resort and The District retail',
    commute: 'Green Valley Ranch is about 20 minutes from the airport and 25 minutes from mid-Strip in typical traffic.',
    amenities: 'Walking access to The District shops and the Green Valley Ranch resort grounds is the location story to photograph.',
    challenge: 'Resort-adjacent homes get compared to hotel finishes. Weak interior photos lose to professionally staged competition.',
    marketingAngle: 'Lead with walkability to The District and outdoor living, then document interior condition without filters.',
    priceContext: 'Ask for a village-level CMA. Resort-adjacent lots and interior lots do not price the same.',
    related: [
      { href: '/neighborhoods/green-valley', anchor: 'Green Valley Henderson homes' },
      { href: '/condos/the-district', anchor: 'District at Green Valley condos' },
      { href: '/neighborhoods/henderson', anchor: 'Henderson expired listing help' },
    ],
  },
  {
    slug: 'anthem',
    name: 'Anthem',
    city: 'Henderson',
    region: 'south Henderson foothills',
    propertyMix: 'production homes, view lots, and golf-course properties',
    commute: 'Anthem is typically 25–35 minutes from the Strip and 20–30 minutes from the airport.',
    amenities: 'Anthem Country Club, trailheads, and hill views are the physical features to capture at twilight.',
    challenge: 'View lots get listed like interior lots. If the view is the product, the photography has to prove it.',
    marketingAngle: 'Sequence photos: view, outdoor living, then interiors. Target golf and foothill buyer lists separately from Green Valley.',
    priceContext: 'View premiums are real and also easy to overstate. Use closed view-lot comps, not asking prices.',
    related: [
      { href: '/neighborhoods/anthem-country-club', anchor: 'Anthem Country Club homes' },
      { href: '/neighborhoods/seven-hills', anchor: 'Seven Hills Henderson homes' },
      { href: '/condos/terra-bella', anchor: 'Terra Bella at Anthem condos' },
      { href: '/neighborhoods/henderson', anchor: 'Henderson real estate' },
    ],
  },
  {
    slug: 'anthem-country-club',
    name: 'Anthem Country Club',
    city: 'Henderson',
    region: 'Anthem, Henderson',
    propertyMix: 'golf-course and guard-gated custom and semi-custom homes',
    commute: 'Anthem Country Club is about 30 minutes from mid-Strip in typical traffic.',
    amenities: 'Golf holes, clubhouse access, and mountain backdrops are the features luxury buyers expect to see in the first five photos.',
    challenge: 'Guard-gated golf product cannot be marketed with production-home photography. The first listing often under-invests.',
    marketingAngle: 'Use magazine-level stills, a floor plan, and private-network outreach to golf-course buyers already in Henderson.',
    priceContext: 'Golf-course and off-course homes in the same gate are different products. Comps must match hole, lot, and finish.',
    related: [
      { href: '/neighborhoods/anthem', anchor: 'Anthem Henderson homes' },
      { href: '/neighborhoods/seven-hills', anchor: 'Seven Hills luxury homes' },
      { href: '/luxury-home-wont-sell-las-vegas', anchor: 'Luxury home will not sell' },
    ],
  },
  {
    slug: 'inspirada',
    name: 'Inspirada',
    city: 'Henderson',
    region: 'south Henderson master-planned villages',
    propertyMix: 'newer production homes, townhomes, and clustered plans',
    commute: 'Inspirada runs about 30 minutes to the Strip and 25 minutes to the airport in typical traffic.',
    amenities: 'Parks, village centers, and trail loops are on-site amenities to map in the listing remarks.',
    challenge: 'Similar floor plans sit next to each other. Without finish-level honesty and better media, the listing is interchangeable.',
    marketingAngle: 'Differentiate with lot, outdoor room, and upgrade list. Do not write remarks that could apply to any tract home in south Henderson.',
    priceContext: 'New-resale pricing moves with builder incentives next door. Recheck builder specials before you relist.',
    related: [
      { href: '/neighborhoods/anthem', anchor: 'Anthem homes in Henderson' },
      { href: '/neighborhoods/henderson', anchor: 'Henderson homes that did not sell' },
      { href: '/neighborhoods/seven-hills', anchor: 'Seven Hills Henderson real estate' },
    ],
  },
  {
    slug: 'seven-hills',
    name: 'Seven Hills',
    city: 'Henderson',
    region: 'south Henderson',
    propertyMix: 'guard-gated custom homes, production homes, and view lots',
    commute: 'Seven Hills is about 25–30 minutes from the Strip and 20 minutes from the airport in typical traffic.',
    amenities: 'Gates, golf, and ridge views are the location facts that belong in photo one through photo five.',
    challenge: 'Custom homes listed with production-home budgets look cheap next to neighboring estates.',
    marketingAngle: 'Invest in aerials, twilight, and a floor plan. Then call the Henderson luxury buyer list directly.',
    priceContext: 'Custom Seven Hills pricing is finish- and view-driven. Citywide luxury averages are not a substitute for a CMA.',
    related: [
      { href: '/neighborhoods/anthem', anchor: 'Anthem Henderson real estate' },
      { href: '/neighborhoods/macdonald-ranch', anchor: 'MacDonald Ranch homes' },
      { href: '/luxury-home-wont-sell-las-vegas', anchor: 'Luxury home will not sell in Las Vegas' },
    ],
  },
  {
    slug: 'lake-las-vegas',
    name: 'Lake Las Vegas',
    city: 'Henderson',
    region: 'northeast Henderson lake community',
    propertyMix: 'lake-view condos, villas, and custom homes',
    commute: 'Lake Las Vegas is typically 30–40 minutes from the Strip and 25–35 minutes from the airport.',
    amenities: 'The lake, marina, trails, and resort hotels are the features buyers fly in to see.',
    challenge: 'HOA, rental, and hotel-condo rules confuse out-of-area buyers. Missing documents kill contracts after the first weekend.',
    marketingAngle: 'Put HOA docs, rental rules, and lake-view proof in the first inquiry packet. Do not make buyers hunt.',
    priceContext: 'Lake-view, golf-view, and interior products do not share a price. Never average them.',
    related: [
      { href: '/condos/henderson', anchor: 'Henderson condos' },
      { href: '/neighborhoods/henderson', anchor: 'Henderson expired listings' },
      { href: '/condos/south-shore', anchor: 'South Shore at Lake Las Vegas' },
    ],
  },
  {
    slug: 'centennial-hills',
    name: 'Centennial Hills',
    city: 'Las Vegas',
    region: 'northwest Las Vegas',
    propertyMix: 'two-story production homes, single-story plans, and newer infill',
    commute: 'Centennial Hills is about 25–35 minutes from the Strip and close to US-95 and the 215 Beltway.',
    amenities: 'Floyd Lamb area open space, retail along the 215, and mountain backdrop views are the photo subjects that convert.',
    challenge: 'Northwest inventory is deep. A listing with poor twilight photos disappears against hundreds of similar floor plans.',
    marketingAngle: 'Lead with lot, garage count, and outdoor living. Target northwest Las Vegas buyer lists, not only Strip-adjacent shoppers.',
    priceContext: 'Price against the same builder generation and lot size in Centennial Hills, not against Summerlin West.',
    related: [
      { href: '/neighborhoods/aliante', anchor: 'Aliante North Las Vegas homes' },
      { href: '/neighborhoods/providence', anchor: 'Providence Las Vegas homes' },
      { href: '/neighborhoods/skye-canyon', anchor: 'Skye Canyon homes' },
    ],
  },
  {
    slug: 'aliante',
    name: 'Aliante',
    city: 'North Las Vegas',
    region: 'northwest North Las Vegas',
    propertyMix: 'production homes around the Aliante golf course and casino retail',
    commute: 'Aliante sits on the 215 Beltway, typically 30 minutes from the Strip in light traffic.',
    amenities: 'Golf, the Aliante casino-hotel, and park corridors are on-site amenities to show in the first carousel.',
    challenge: 'Golf-course and off-course homes get lumped together. Buyers notice. So should the remarks.',
    marketingAngle: 'Label golf, park, or interior lot in the headline. Then run media that proves the claim.',
    priceContext: 'North Las Vegas and Las Vegas northwest comps are not interchangeable. Stay inside Aliante and adjacent tracts.',
    related: [
      { href: '/neighborhoods/north-las-vegas', anchor: 'North Las Vegas homes that did not sell' },
      { href: '/neighborhoods/centennial-hills', anchor: 'Centennial Hills homes' },
      { href: '/neighborhoods/providence', anchor: 'Providence Las Vegas real estate' },
    ],
  },
  {
    slug: 'north-las-vegas',
    name: 'North Las Vegas',
    city: 'North Las Vegas',
    region: 'north of downtown Las Vegas',
    propertyMix: 'production homes, newer master-planned villages, and infill',
    commute: 'North Las Vegas offers I-15 and 215 access; downtown is often 15–25 minutes depending on the neighborhood.',
    amenities: 'Parks, recreation centers, and newer village amenities vary by tract — name the actual village in the listing.',
    challenge: 'Citywide “North Las Vegas” ads ignore village differences. Buyers filter by year built, lot, and HOA.',
    marketingAngle: 'Market the village, not the city label. Pair that with honest condition photos and a current CMA.',
    priceContext: 'North Las Vegas pricing is tract-specific. Expired listings in the same year-built band are the comps that matter.',
    related: [
      { href: '/neighborhoods/aliante', anchor: 'Aliante homes' },
      { href: '/neighborhoods/centennial-hills', anchor: 'Centennial Hills real estate' },
      { href: '/sell-house-fast-las-vegas', anchor: 'Sell a house fast in Las Vegas' },
    ],
  },
  {
    slug: 'boulder-city',
    name: 'Boulder City',
    city: 'Boulder City',
    region: 'southeast of Henderson, near Hoover Dam',
    propertyMix: 'mid-century homes, custom desert lots, and limited new construction',
    commute: 'Boulder City is about 30–40 minutes from the airport and 40 minutes from mid-Strip in typical traffic.',
    amenities: 'Historic downtown, Lake Mead access, and desert open space are the location facts out-of-area buyers need in writing.',
    challenge: 'Boulder City’s slower inventory cycle punishes stale photos. A six-month-old listing looks abandoned.',
    marketingAngle: 'Explain lot, construction type, and downtown distance in the first 80 words. Then target Lake Mead and Henderson overflow buyers.',
    priceContext: 'Do not price Boulder City off Henderson averages. The buyer pool and housing stock are different.',
    related: [
      { href: '/neighborhoods/henderson', anchor: 'Henderson homes that did not sell' },
      { href: '/neighborhoods/lake-las-vegas', anchor: 'Lake Las Vegas homes' },
      { href: '/contact', anchor: 'Contact Dr. Jan Duffy' },
    ],
  },
  {
    slug: 'spring-valley',
    name: 'Spring Valley',
    city: 'Las Vegas',
    region: 'southwest unincorporated Clark County',
    propertyMix: '1970s–2000s single-family homes, townhomes, and infill',
    commute: 'Spring Valley sits near the 215 and I-15, typically 15–20 minutes from the Strip.',
    amenities: 'Chinatown retail corridors, parks, and golf along the southwest are nearby services to mention with commute times.',
    challenge: 'Wide age bands mean a 1988 home listed like a 2018 home fails inspection. Disclose updates with dates.',
    marketingAngle: 'Put roof, HVAC, and remodel years in remarks. Spring Valley buyers read those lines before they book a tour.',
    priceContext: 'Price by year built, lot, and update level inside Spring Valley — not against Summerlin new-resale.',
    related: [
      { href: '/neighborhoods/enterprise', anchor: 'Enterprise Las Vegas homes' },
      { href: '/neighborhoods/rhodes-ranch', anchor: 'Rhodes Ranch homes' },
      { href: '/neighborhoods/the-lakes', anchor: 'The Lakes Las Vegas homes' },
    ],
  },
  {
    slug: 'enterprise',
    name: 'Enterprise',
    city: 'Las Vegas',
    region: 'south Las Vegas near the 215',
    propertyMix: 'newer production homes, townhomes, and infill near the south 215',
    commute: 'Enterprise is often 15–25 minutes from the Strip and 10–20 minutes from the airport.',
    amenities: 'South Strip access, 215 retail, and mountain views on some streets are the facts to photograph.',
    challenge: 'Builder competition is constant. A resale with weak media cannot beat a model home weekend.',
    marketingAngle: 'Show move-in condition, blinds, landscaping, and window treatments that builders often exclude.',
    priceContext: 'Watch nearby builder incentives. A relist that ignores them will sit.',
    related: [
      { href: '/neighborhoods/southern-highlands', anchor: 'Southern Highlands homes' },
      { href: '/neighborhoods/mountains-edge', anchor: 'Mountains Edge homes' },
      { href: '/neighborhoods/spring-valley', anchor: 'Spring Valley homes' },
    ],
  },
  {
    slug: 'rhodes-ranch',
    name: 'Rhodes Ranch',
    city: 'Las Vegas',
    region: 'southwest Las Vegas',
    propertyMix: 'golf-course homes, production plans, and guard-gated pockets',
    commute: 'Rhodes Ranch is about 20 minutes from the Strip via the 215 in typical traffic.',
    amenities: 'Golf holes, clubhouse, and mountain views are the features that must appear before interior filler shots.',
    challenge: 'Golf-course claims without hole photos get skipped. Interior-lot homes overpriced as golf product expire.',
    marketingAngle: 'Tell the truth about the lot. Then market golf and non-golf to different lists.',
    priceContext: 'Golf-course premiums need golf-course closed comps. Do not blend them with interior lots.',
    related: [
      { href: '/neighborhoods/spanish-trail', anchor: 'Spanish Trail luxury homes' },
      { href: '/neighborhoods/enterprise', anchor: 'Enterprise Las Vegas homes' },
      { href: '/neighborhoods/spring-valley', anchor: 'Spring Valley real estate' },
    ],
  },
  {
    slug: 'queensridge',
    name: 'Queensridge',
    city: 'Las Vegas',
    region: 'west of the 215 near Summerlin',
    propertyMix: 'guard-gated custom homes and luxury townhomes',
    commute: 'Queensridge is about 20 minutes from the Strip and minutes from Downtown Summerlin.',
    amenities: 'Gates, custom architecture, and proximity to Red Rock Canyon drives are the luxury facts to lead with.',
    challenge: 'Custom homes listed with production budgets look unfinished next to One Queensridge Place and neighboring estates.',
    marketingAngle: 'Use architectural photography, a floor plan, and a private luxury list. The media has to match the gate.',
    priceContext: 'Queensridge custom pricing is not a Summerlin village average. Match lot, square footage, and finish.',
    related: [
      { href: '/condos/one-queensridge', anchor: 'One Queensridge Place condos' },
      { href: '/neighborhoods/summerlin', anchor: 'Summerlin homes that did not sell' },
      { href: '/neighborhoods/peccole-ranch', anchor: 'Peccole Ranch homes' },
    ],
  },
  {
    slug: 'peccole-ranch',
    name: 'Peccole Ranch',
    city: 'Las Vegas',
    region: 'west Las Vegas near the 215',
    propertyMix: '1980s–1990s single-family homes with mature landscaping',
    commute: 'Peccole Ranch is about 15–20 minutes from the Strip and close to Summerlin Parkway.',
    amenities: 'Tree canopy, park belts, and west-valley access are the location facts newer tracts cannot copy.',
    challenge: 'Mature homes with original kitchens get listed like remodeled comps. Buyers walk. Disclose what is original.',
    marketingAngle: 'Show lot size, trees, and actual interior age. Then price against similar-year remodeled and un-remodeled pairs.',
    priceContext: 'Update level drives Peccole Ranch value more than a west-valley average.',
    related: [
      { href: '/neighborhoods/the-lakes', anchor: 'The Lakes Las Vegas homes' },
      { href: '/neighborhoods/queensridge', anchor: 'Queensridge luxury homes' },
      { href: '/neighborhoods/summerlin', anchor: 'Summerlin real estate' },
    ],
  },
  {
    slug: 'the-lakes',
    name: 'The Lakes',
    city: 'Las Vegas',
    region: 'west Las Vegas',
    propertyMix: 'lake-view and interior single-family homes and townhomes',
    commute: 'The Lakes is about 15–20 minutes from the Strip and near the 215 / Sahara area.',
    amenities: 'Lakes, walking paths, and west-valley retail are the features to prove with exterior photography.',
    challenge: 'Lake-view premiums collapse if photos do not show water. Interior lots listed as “The Lakes lifestyle” without water lose trust.',
    marketingAngle: 'Headline the lot type. Sequence water, path, then interiors.',
    priceContext: 'Waterfront, water-view, and interior products need separate comps.',
    related: [
      { href: '/neighborhoods/desert-shores', anchor: 'Desert Shores homes' },
      { href: '/neighborhoods/peccole-ranch', anchor: 'Peccole Ranch homes' },
      { href: '/neighborhoods/spring-valley', anchor: 'Spring Valley homes' },
    ],
  },
  {
    slug: 'spanish-trail',
    name: 'Spanish Trail',
    city: 'Las Vegas',
    region: 'southwest Las Vegas guard-gated golf community',
    propertyMix: 'custom golf-course estates and luxury production homes',
    commute: 'Spanish Trail is about 15 minutes from the Strip via I-15 / 215 in typical traffic.',
    amenities: 'Golf, tennis, and guard gates are the amenity set luxury buyers expect in the first carousel.',
    challenge: 'Estate listings with $200 photography do not clear this gate. The first agent often under-invested.',
    marketingAngle: 'Fund twilight, aerials, and a floor plan. Then work the southwest luxury list and golf-course buyers.',
    priceContext: 'Spanish Trail comps must match golf vs off-course and remodel vintage. Do not use Rhodes Ranch as a proxy.',
    related: [
      { href: '/neighborhoods/rhodes-ranch', anchor: 'Rhodes Ranch golf homes' },
      { href: '/luxury-home-wont-sell-las-vegas', anchor: 'Luxury home will not sell' },
      { href: '/neighborhoods/summerlin-west', anchor: 'Summerlin West estates' },
    ],
  },
  {
    slug: 'downtown-summerlin',
    name: 'Downtown Summerlin',
    city: 'Las Vegas',
    region: 'Summerlin retail and residential core',
    propertyMix: 'adjacent single-family, townhomes, and nearby high-density residences',
    commute: 'Downtown Summerlin is the west-valley retail hub; the Strip is typically 20 minutes.',
    amenities: 'Shopping, dining, and event lawns at Downtown Summerlin are the walkable location story.',
    challenge: 'Homes near the retail core get noise and parking questions. Hide those and the tour dies at inspection.',
    marketingAngle: 'State walk times to specific retailers. Photograph outdoor living at dusk when the core is lit.',
    priceContext: 'Proximity to the core can add or subtract value depending on street. Use street-level comps.',
    related: [
      { href: '/neighborhoods/summerlin', anchor: 'Summerlin homes that did not sell' },
      { href: '/neighborhoods/summerlin-west', anchor: 'Summerlin West homes' },
      { href: '/condos/summerlin', anchor: 'Summerlin condos' },
    ],
  },
  {
    slug: 'desert-shores',
    name: 'Desert Shores',
    city: 'Las Vegas',
    region: 'northwest Las Vegas lake community',
    propertyMix: 'lake-view homes, townhomes, and interior lots around four lakes',
    commute: 'Desert Shores is about 20 minutes from downtown Las Vegas and 25 minutes from the Strip in typical traffic.',
    amenities: 'Lakes, paths, and beach clubs are the amenities that must appear in photo one if you are claiming water.',
    challenge: 'Water claims without water photos are the fastest way to burn a Desert Shores listing.',
    marketingAngle: 'Prove the water. Then market lake vs interior products on different buyer lists.',
    priceContext: 'Lake-front and interior Desert Shores homes are different products. Do not average them.',
    related: [
      { href: '/neighborhoods/the-lakes', anchor: 'The Lakes Las Vegas homes' },
      { href: '/neighborhoods/centennial-hills', anchor: 'Centennial Hills homes' },
      { href: '/neighborhoods/summerlin', anchor: 'Summerlin real estate' },
    ],
  },
  {
    slug: 'providence',
    name: 'Providence',
    city: 'Las Vegas',
    region: 'northwest Las Vegas master-planned community',
    propertyMix: '2000s production homes, townhomes, and some golf-adjacent lots',
    commute: 'Providence sits near the 215 and US-95, typically 25–30 minutes from the Strip.',
    amenities: 'Parks, village retail, and mountain backdrop views are on-site features to map in remarks.',
    challenge: 'Similar floor plans require upgrade honesty. “Completely remodeled” that is only paint will expire.',
    marketingAngle: 'List upgrades with years. Photograph outdoor living. Target northwest buyer lists.',
    priceContext: 'Match year built and lot inside Providence. Centennial Hills is a reference, not a substitute.',
    related: [
      { href: '/neighborhoods/centennial-hills', anchor: 'Centennial Hills homes' },
      { href: '/neighborhoods/aliante', anchor: 'Aliante homes' },
      { href: '/neighborhoods/skye-canyon', anchor: 'Skye Canyon homes' },
    ],
  },
  {
    slug: 'tournament-hills',
    name: 'Tournament Hills',
    city: 'Las Vegas',
    region: 'Summerlin',
    propertyMix: 'golf-adjacent and village single-family homes in Summerlin',
    commute: 'Tournament Hills is inside Summerlin, typically 20 minutes from the Strip.',
    amenities: 'TPC at Summerlin proximity and village parks are the location facts to show.',
    challenge: 'Golf-adjacent vs true golf-course lots get confused in remarks. Buyers who drive out feel misled.',
    marketingAngle: 'State the lot relationship to the course in one sentence. Then prove it with aerials.',
    priceContext: 'Summerlin village comps plus lot type. Do not use The Ridges as a Tournament Hills proxy.',
    related: [
      { href: '/neighborhoods/summerlin', anchor: 'Summerlin homes that did not sell' },
      { href: '/neighborhoods/summerlin-west', anchor: 'Summerlin West luxury homes' },
      { href: '/neighborhoods/the-ridges', anchor: 'The Ridges Summerlin estates' },
    ],
  },
]

const bySlug = new Map(records.map((record) => [record.slug, record]))

export function getDynamicNeighborhoodSlugs(): string[] {
  return records.map((record) => record.slug)
}

export function getNeighborhoodRecord(slug: string): PlaceRecord | undefined {
  return bySlug.get(slug)
}

export function getNeighborhoodPage(slug: string): SeoPageContent | undefined {
  const record = bySlug.get(slug)
  if (!record) return undefined
  return buildPlacePage(record, 'neighborhood')
}

export function getNeighborhoodHubLinks(): Array<{ href: string; name: string; blurb: string }> {
  const dynamic = records.map((record) => ({
    href: `/neighborhoods/${record.slug}`,
    name: record.name,
    blurb: record.propertyMix,
  }))
  const existing = [
    { href: '/neighborhoods/summerlin-west', name: 'Summerlin West', blurb: 'Luxury estates west of the 215' },
    { href: '/neighborhoods/the-ridges', name: 'The Ridges', blurb: 'Custom estates in Summerlin' },
    { href: '/neighborhoods/red-rock-country-club', name: 'Red Rock Country Club', blurb: 'Golf-course homes near Red Rock' },
    { href: '/neighborhoods/the-summit', name: 'The Summit', blurb: 'Gated Summerlin village' },
    { href: '/neighborhoods/macdonald-ranch', name: 'MacDonald Ranch', blurb: 'Henderson custom and production homes' },
    { href: '/neighborhoods/southern-highlands', name: 'Southern Highlands', blurb: 'Master-planned south valley homes' },
    { href: '/neighborhoods/skye-canyon', name: 'Skye Canyon', blurb: 'Northwest master-planned homes' },
    { href: '/neighborhoods/mountains-edge', name: 'Mountains Edge', blurb: 'Southwest production homes and parks' },
    { href: '/neighborhoods/del-webb-north-ranch', name: 'Del Webb North Ranch', blurb: 'Age-restricted Del Webb community' },
  ]
  return [...existing, ...dynamic]
}
